### ISSUE TITLE
494 Error when clicking Details link for Bundlewatch check

### ISSUE THREAD

**Issue by dhruska** [bundlewatch/service#34]
This ticket is maybe more appropriate for the service repository, given it's happening on the Bundlewatch server: https://github.com/bundlewatch/bundlewatch/issues/68

**Comment by iamogbz** [comment]
@dhruska is this still happening? Can not reproduce

**Comment by iamogbz** [comment]
Closing in favour of tracking here https://github.com/bundlewatch/bundlewatch/issues/68
