### ISSUE TITLE
Domain bundlewatch.io have expired

### ISSUE THREAD

**Issue by esroyo** [bundlewatch/service#722]
@jakebolam @charpeni it seems the main domain and its subdomains have expired:
https://whois.gandi.net/en/results?search=bundlewatch.io

```
Domain Name: bundlewatch.io
Registry Domain ID: D503300000099273120-LRMS
Registrar WHOIS Server: whois.gandi.net
Registrar URL: http://www.gandi.net
Updated Date: 2024-04-30T23:36:23Z
Creation Date: 2018-04-30T23:34:54Z
Registrar Registration Expiration Date: 2024-05-01T01:34:54Z
```

I hope it can be sorted out.

Please also consider enabling some way to sponsor the project/organization.

Thanks a lot! :pray:

**Comment by charpeni** [comment]
Thanks for flagging it, it has been solved since then!

Working on a way to sponsor this project 🙏
